# Generated by Django 2.2.4 on 2021-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
